# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ServerStatusGet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, value: str=None, timestamp: datetime=None, status: str=None):  # noqa: E501
        """ServerStatusGet - a model defined in Swagger

        :param value: The value of this ServerStatusGet.  # noqa: E501
        :type value: str
        :param timestamp: The timestamp of this ServerStatusGet.  # noqa: E501
        :type timestamp: datetime
        :param status: The status of this ServerStatusGet.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'value': str,
            'timestamp': datetime,
            'status': str
        }

        self.attribute_map = {
            'value': 'value',
            'timestamp': 'timestamp',
            'status': 'status'
        }
        self._value = value
        self._timestamp = timestamp
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'ServerStatusGet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServerStatusGet of this ServerStatusGet.  # noqa: E501
        :rtype: ServerStatusGet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> str:
        """Gets the value of this ServerStatusGet.

        The servers status  # noqa: E501

        :return: The value of this ServerStatusGet.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this ServerStatusGet.

        The servers status  # noqa: E501

        :param value: The value of this ServerStatusGet.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this ServerStatusGet.


        :return: The timestamp of this ServerStatusGet.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this ServerStatusGet.


        :param timestamp: The timestamp of this ServerStatusGet.
        :type timestamp: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def status(self) -> str:
        """Gets the status of this ServerStatusGet.


        :return: The status of this ServerStatusGet.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ServerStatusGet.


        :param status: The status of this ServerStatusGet.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
