# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TemperaturePost(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, value: int=None):  # noqa: E501
        """TemperaturePost - a model defined in Swagger

        :param id: The id of this TemperaturePost.  # noqa: E501
        :type id: str
        :param value: The value of this TemperaturePost.  # noqa: E501
        :type value: int
        """
        self.swagger_types = {
            'id': str,
            'value': int
        }

        self.attribute_map = {
            'id': 'id',
            'value': 'value'
        }
        self._id = id
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'TemperaturePost':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TemperaturePost of this TemperaturePost.  # noqa: E501
        :rtype: TemperaturePost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this TemperaturePost.

        the unique identifier for the zone  # noqa: E501

        :return: The id of this TemperaturePost.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this TemperaturePost.

        the unique identifier for the zone  # noqa: E501

        :param id: The id of this TemperaturePost.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def value(self) -> int:
        """Gets the value of this TemperaturePost.

        the temperature in \"Kelvin\", step=0.1K  # noqa: E501

        :return: The value of this TemperaturePost.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this TemperaturePost.

        the temperature in \"Kelvin\", step=0.1K  # noqa: E501

        :param value: The value of this TemperaturePost.
        :type value: int
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
