openapi: 3.0.0
info:
  title: home-iot-api
  description: The API for the OVK-1 IOT project
  version: 1.0.6
servers:
- url: https://virtserver.swaggerhub.com/OVK/OVK_mob1/1.0.6
  description: SwaggerHub API Auto Mocking
paths:
  /temperatureRoom/:
    get:
      tags:
      - Environment
      operationId: temperature_room
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureSensorGet'
        "404":
          description: some errors...
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
  /temperatureWater/:
    get:
      tags:
      - Environment
      operationId: temperature_water
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureSensorGet'
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
  /temperatureWeather:
    get:
      tags:
      - Environment
      summary: Call current weather data for one location
      operationId: temperature_weather
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureSensorGet'
        "404":
          description: some errors...
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
  /targetTemperature:
    get:
      tags:
      - Environment
      operationId: target_temperature
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureTargetGet'
        "404":
          description: some errors...
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
  /temperatureComfort:
    get:
      tags:
      - Environment
      operationId: temperature_comfort
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureTargetGet'
        "404":
          description: some errors...
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
  /temperatureEconom:
    get:
      tags:
      - Environment
      operationId: temperature_econom
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureTargetGet'
        "404":
          description: some errors...
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
  /updateTargetTemperature:
    post:
      tags:
      - Environment
      description: target room temperature
      operationId: update_target_temperature
      requestBody:
        description: target t
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemperaturePost'
        required: true
      responses:
        "200":
          description: Status of the operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "404":
          description: some errors...
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
  /updateComfortTemperature:
    post:
      tags:
      - Environment
      description: target room temperature
      operationId: update_comfort_temperature
      requestBody:
        description: Comfort t
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemperaturePost'
        required: true
      responses:
        "200":
          description: Status of the operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "404":
          description: some errors...
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
  /updateEconomTemperature:
    post:
      tags:
      - Environment
      description: target room temperature
      operationId: update_econom_temperature
      requestBody:
        description: Econom t
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemperaturePost'
        required: true
      responses:
        "200":
          description: Status of the operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
components:
  schemas:
    TemperatureTargetGet:
      required:
      - id
      - value
      type: object
      properties:
        id:
          type: string
          description: the unique identifier for the zone
        name:
          type: string
        value:
          type: integer
          description: the temperature in "Kelvin", step=0.1K
          format: int16
      description: temperature target value
      example:
        name: name
        id: id
        value: 0
    TemperatureSensorGet:
      required:
      - id
      - status
      - timestamp
      - value
      type: object
      properties:
        id:
          type: string
          description: the unique identifier for the zone
        name:
          type: string
        value:
          type: integer
          description: the temperature in "Kelvin", step=0.1K
          format: int16
        timestamp:
          type: string
          description: the timestamp when the temperature was measured
          format: date-time
        status:
          type: string
      description: temperature sensor value and status (normal, failed and so on)
      example:
        name: name
        id: id
        value: 0
        timestamp: 2000-01-23T04:56:07.000+00:00
        status: status
    TemperaturePost:
      required:
      - id
      - value
      type: object
      properties:
        id:
          type: string
          description: the unique identifier for the zone
        value:
          type: integer
          description: the temperature in "Kelvin", step=0.1K
          format: int16
      description: Target temperature from user
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          example: everything is ok
      example:
        code: 0
        message: everything is ok
    HeaterState:
      type: object
      properties:
        id:
          type: string
        state:
          type: string
      description: Just for case, not used yet
    DeviceState:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        lastUpdate:
          type: string
          format: date-time
        level:
          type: integer
          format: int32
      description: Just for case, not used yet
    DeviceRegistrationInfo:
      type: object
      properties:
        uri:
          type: string
          format: uri
          example: http://10.0.0.220:8080
        id:
          type: string
          format: uuid
          example: 0729a580-2240-11e6-9eb5-0002a5d5c51b
      description: Just for case, not used yet
    Errors:
      type: object
      properties:
        status:
          type: integer
        type:
          type: string
        message:
          type: string

